sudo: true
dist: trusty

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

cache:
  directories:
    - ./node_modules      

jobs:
  include:
    - stage: Unit Test & e2e Test
      language: node_js
      node_js: "12.3.1"
      before_script: 
        - npm i -g karma
        - npm i
      script: ng test
    - # stage name not required, parallel jobs
      language: node_js
      node_js: "8.11.1"    
      before_script: 
        - npm i
      script: ng e2e 
    - stage: Build & Release Docker images
      script:
        - echo "Building image marcocab/Klondike-app:dev..." 
        - docker build -t marcocab/Klondike-app:dev
        - echo "done." 
        - echo "Building tag marcocab/Klondike-app:dev --> marcocab/Klondike-app:latest..." 
        - docker tag marcocab/Klondike-app:dev marcocab/Klondike-app:latest
        - echo "done." 
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
        - echo "Push marcocab/Klondike-app:dev..." 
        - docker push marcocab/Klondike-app:dev
        - echo "done." 
        - echo "Push marcocab/Klondike-app:latest..." 
        - docker push marcocab/Klondike-app:latest
        - echo "done." 