os: linux
dist: trusty

language: node_js

node_js:
  - 12.4.0

addons:
  chrome: stable

before_script:
  - set -e
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - ng lint
  - ng test --watch=false
  - npm run e2e --webdriverUpdate=false