os: linux
dist: trusty

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

jobs:
  include:
    - stage: Linting and Unit testing
      language: node_js
      node_js: "12.3.1"
      before_script: 
        - npm install
      script: ng lint 
    - # stage name not required, parallel jobs
      language: node_js
      node_js: "12.3.1" 
      before_script: 
        - npm install
      script: ng test --watch=false
    - stage: Testing e2e
      language: node_js
      node_js: "12.3.1" 
      before_script: 
        - npm install
      script: ng e2e