os: linux
dist: trusty

language: node_js

node_js:
  - 12.4.0

addons:
  chrome: beta

before_script:
  - set -e
  - npm install
  - npm run build:library
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run test
  - npm run e2e