os: linux
dist: xenial

language: ruby

services: docker

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules
jobs:
  include:
    - stage: Testing phase
      name: Lint.
      language: node_js
      node_js: "12.3.1"
      before_script: 
        - npm install
      script: ng lint 
    - # stage name not required, parallel jobs
      name: Unit testing
      language: node_js
      node_js: "12.3.1" 
      before_script: 
        - npm install
      script: npm run test-ci
    - # stage name not required, parallel jobs
      name: End to end testing.
      language: node_js
      node_js: "12.3.1" 
      before_script: 
        - npm install
      script: npm run e2e-ci
    - stage: Release phase
      name: Docker release
      script: bash build.sh --release-ci