apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.usvc.name }}-deployment
    labels:
       app: {{ .Values.usvc.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.usvc.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.usvc.name }}
    spec:
        containers:
        - name: {{ .Values.usvc.name }}
          image: {{ .Values.global.registry }}{{ .Values.usvc.image.name }}:{{ .Values.usvc.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: {{ .Values.usvc.port }}
