apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.global.name }}-deployment
    labels:
       app: {{ .Values.global.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.global.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}
    spec:
        containers:
        - name: {{ .Values.global.name }}
          image: {{ .Values.global.registry }}{{ .Values.global.image.name }}:{{ .Values.global.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: {{ .Values.global.port }}  

---    
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.global.name}}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.global.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.global.port }}
